---
# tasks file for roles

- name: Testing variables with default dir
  debug:
    msg: |
      {{ messagedefaults }}

- import_tasks: messagevars.yaml
  tags: message

- include_tasks: copy.yaml
...
