---
- hosts: groupall
  become: true
  user: ansible_user
  tasks:
    - name: Playing with special vars
      debug:
        msg: |
          Testing ansible in the version {{ ansible_version }}
          My groups in the iventory are {{ inventory_hostname }}
...
