---
- hosts: group2
  vars:
    user1:
      user_name: atest
      user_home: /home/atest
      user_description: array with variables
  become: true
  user: ansible_user
  tasks:
    - name: Create user {{ user1.user_name }}
      user:
        name: "{{ user1.user_name }}"
        home: "{{ user1['user_home'] }}"
        comment: "{{ user1.user_description }}"
...
