---
- name: Install {{ pkg }}
  apt:
    name: "{{ pkg }}"
    state: latest
  tags:
    - install

- name: Start services {{ svc }}
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ svc }}"
  tags:
    - startservice
    - install
...
